/*
 * Mellov API
 * Mellov API
 *
 * OpenAPI spec version: 1.2.3
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MellovApi) {
      root.MellovApi = {};
    }
    root.MellovApi.YtVideoItem = factory(root.MellovApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The YtVideoItem model module.
   * @module model/YtVideoItem
   * @version 1.2.3
   */

  /**
   * Constructs a new <code>YtVideoItem</code>.
   * @alias module:model/YtVideoItem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>YtVideoItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/YtVideoItem} obj Optional instance to populate.
   * @return {module:model/YtVideoItem} The populated <code>YtVideoItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('videoId'))
        obj.videoId = ApiClient.convertToType(data['videoId'], 'String');
      if (data.hasOwnProperty('thumbnailUrl'))
        obj.thumbnailUrl = ApiClient.convertToType(data['thumbnailUrl'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {String} videoId
   */
  exports.prototype.videoId = undefined;

  /**
   * @member {String} thumbnailUrl
   */
  exports.prototype.thumbnailUrl = undefined;


  return exports;

}));
