/*
 * Mellov API
 * Mellov API
 *
 * OpenAPI spec version: 1.2.3
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.22
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimpleResponse', 'model/UserPost'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SimpleResponse'), require('../model/UserPost'));
  } else {
    // Browser globals (root is window)
    if (!root.MellovApi) {
      root.MellovApi = {};
    }
    root.MellovApi.DevelopersApi = factory(root.MellovApi.ApiClient, root.MellovApi.SimpleResponse, root.MellovApi.UserPost);
  }
}(this, function(ApiClient, SimpleResponse, UserPost) {
  'use strict';

  /**
   * Developers service.
   * @module api/DevelopersApi
   * @version 1.2.3
   */

  /**
   * Constructs a new DevelopersApi. 
   * @alias module:api/DevelopersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the signInUser operation.
     * @callback module:api/DevelopersApi~signInUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SimpleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * login user
     * signs in user
     * @param {Object} opts Optional parameters
     * @param {module:model/UserPost} opts.userCredentials User's credentials
     * @param {module:api/DevelopersApi~signInUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SimpleResponse}
     */
    this.signInUser = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['userCredentials'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SimpleResponse;

      return this.apiClient.callApi(
        '/user/login', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the signUpUser operation.
     * @callback module:api/DevelopersApi~signUpUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SimpleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * register new user
     * signs up new user
     * @param {Object} opts Optional parameters
     * @param {module:model/UserPost} opts.userCredentials User's credentials
     * @param {module:api/DevelopersApi~signUpUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SimpleResponse}
     */
    this.signUpUser = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['userCredentials'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SimpleResponse;

      return this.apiClient.callApi(
        '/user/register', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
